# Generated by Django 5.0.3 on 2024-03-09 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learnathonApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q1', models.CharField(choices=[('Very satisfied', 'Very satisfied'), ('Satisfied', 'Satisfied'), ('Neutral', 'Neutral'), ('Dissatisfied', 'Dissatisfied'), ('Very dissatisfied', 'Very dissatisfied')], max_length=50)),
                ('q2', models.CharField(choices=[('Very likely', 'Very likely'), ('Likely', 'Likely'), ('Neutral', 'Neutral'), ('Unlikely', 'Unlikely'), ('Very unlikely', 'Very unlikely')], max_length=50)),
                ('q3', models.CharField(choices=[('Excellent', 'Excellent'), ('Very good', 'Very good'), ('Good', 'Good'), ('Fair', 'Fair'), ('Poor', 'Poor')], max_length=50)),
                ('q4', models.CharField(choices=[('Very satisfied', 'Very satisfied'), ('Satisfied', 'Satisfied'), ('Neutral', 'Neutral'), ('Dissatisfied', 'Dissatisfied'), ('Very dissatisfied', 'Very dissatisfied')], max_length=50)),
                ('q5', models.CharField(choices=[('Very satisfied', 'Very satisfied'), ('Satisfied', 'Satisfied'), ('Neutral', 'Neutral'), ('Dissatisfied', 'Dissatisfied'), ('Very dissatisfied', 'Very dissatisfied')], max_length=50)),
                ('q6', models.CharField(choices=[('Excellent', 'Excellent'), ('Very good', 'Very good'), ('Good', 'Good'), ('Fair', 'Fair'), ('Poor', 'Poor')], max_length=50)),
                ('q7', models.CharField(choices=[('Very satisfied', 'Very satisfied'), ('Satisfied', 'Satisfied'), ('Neutral', 'Neutral'), ('Dissatisfied', 'Dissatisfied'), ('Very dissatisfied', 'Very dissatisfied')], max_length=50)),
                ('q8', models.CharField(choices=[('Very likely', 'Very likely'), ('Likely', 'Likely'), ('Neutral', 'Neutral'), ('Unlikely', 'Unlikely'), ('Very unlikely', 'Very unlikely')], max_length=50)),
                ('q9', models.CharField(choices=[('Very likely', 'Very likely'), ('Likely', 'Likely'), ('Neutral', 'Neutral'), ('Unlikely', 'Unlikely'), ('Very unlikely', 'Very unlikely')], max_length=50)),
                ('q10', models.CharField(choices=[('Very satisfied', 'Very satisfied'), ('Satisfied', 'Satisfied'), ('Neutral', 'Neutral'), ('Dissatisfied', 'Dissatisfied'), ('Very dissatisfied', 'Very dissatisfied')], max_length=50)),
                ('q11', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
